---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cni-infoblox-client
  namespace: kube-system
spec:
  selector:
      matchLabels:
        name: cni-infoblox-client
  template:
    metadata:
      labels:
        name: cni-infoblox-client
    spec:
      terminationGracePeriodSeconds: 60
      hostNetwork: true
      containers:
      - image: infoblox/cni-infoblox-client
        name: cni-infoblox-client
        volumeMounts:
            - mountPath: /run/cni
              name: socket-dir
        imagePullPolicy: Always
        args:
          - "--grid-host=192.168.124.200"
          - "--wapi-port=443"
          - "--wapi-username=admin"
          - "--wapi-version=2.5"
          - "--socket-dir=/run/cni"
          - "--driver-name=infoblox"
          - "--cluster-name=cluster Name"
          - "--ssl-verify=false"
          - "--network-view=default"
        env:
          - name: WAPI_PASSWORD
            valueFrom:
              secretKeyRef:
                name: infoblox-secret
                key: wapi-password
      volumes:
        - name: socket-dir
          hostPath:
            path: /run/cni
---
apiVersion: v1
kind: Secret
metadata:
  name: infoblox-secret
  namespace: kube-system
type: Opaque
data:
  wapi-password: aW5mb2Jsb3g=
